import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import AppHeader from '@/../lib/components/AppLayout/MiniSidebarToggle/AppHeader'
import AppSidebar from '@/../lib/components/AppLayout/MiniSidebarToggle/AppSidebar'
import AppThemeSetting from 'lib/components/AppThemeSetting'

import routesConfig from '../core/AppRoutes/routeConfig';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AppHeader />
        <AppSidebar routesConfig={routesConfig}/>
        <AppThemeSetting />
        <div>Hi Cash</div>
      </main>
    </>
  )
}
